name: Set Created Date

on:
  projects_v2_item:
    types: [created]

jobs:
  set-created-date:
    runs-on: ubuntu-latest
    if: github.event.projects_v2_item.project_node_id == 'PVT_kwDOAGc3Zs4AIkji'
    steps:
      - name: Set Created Date
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const projectId = 'PVT_kwDOAGc3Zs4AIkji'; // Your project ID
            const fieldId = process.env.CREATED_DATE_FIELD_ID;
            const itemId = context.payload.projects_v2_item.node_id;
            
            // Get the issue to find its creation date
            const contentNodeId = context.payload.projects_v2_item.content_node_id;
            
            const issueQuery = `
              query($nodeId: ID!) {
                node(id: $nodeId) {
                  ... on Issue {
                    createdAt
                  }
                }
              }
            `;
            
            const issueData = await github.graphql(issueQuery, {
              nodeId: contentNodeId
            });
            
            if (!issueData.node || !issueData.node.createdAt) {
              console.log('Could not get issue creation date');
              return;
            }
            
            const createdDate = issueData.node.createdAt.split('T')[0];
            console.log(`Setting Created Date to: ${createdDate}`);
            
            // Update the Created Date field
            const mutation = `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $date: Date!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId
                  itemId: $itemId
                  fieldId: $fieldId
                  value: { date: $date }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `;
            
            await github.graphql(mutation, {
              projectId,
              itemId,
              fieldId,
              date: createdDate
            });
            
            console.log('✓ Created Date set successfully');
        env:
          CREATED_DATE_FIELD_ID: 'PVTF_lADOAGc3Zs4AIkjizg3CE8o'

